# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: mangopay2-java-sdk-cd

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      # It pushes any tags that contain a v. ex: v1.16.1
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Update OpenSSL
        run: sudo apt-get install openssl
      - name: OpenSSL Version
        run: openssl version
      - name: Decrypt Security Key
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_TOKEN }}
          HEX_KEY: ${{ secrets.HEX_KEY }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SIGNING_PASSWORD: $ {{ secrets.SIGNING_PASSWORD }}
        run: openssl aes-256-cbc -d -in .utility/secring.gpg.enc -out .utility/secring.gpg -k $PASSWORD
      - name: Give permissions to file
        run: chmod +x .utility/initiate-publish.sh
      - name: Check decrypt step
        run: ls -a .utility/
      - name: Publish
        run: ./gradlew publish -PnexusUsername=$MAVEN_USERNAME -PnexusPassword=$MAVEN_PASSWORD -Psigning.keyId=9942FDF1 -Psigning.password=$SIGNING_PASSWORD -Psigning.secretKeyRingFile=.utility/secring.gpg
      - name: Close and publish
        run: ./gradlew closeAndReleaseRepository -PnexusUsername=$MAVEN_USERNAME -PnexusPassword=$MAVEN_PASSWORD
