# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: mangopay2-java-sdk-ci

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      # It pushes any tags that contain a v. ex: v1.16.1
      - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: gradle assemble
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://oss.sonatype.org/service/local/staging/deploy/maven2
          username: ${{ secrets.MAVEN_USERNAME }}
          password: ${{ secrets.MAVEN_TOKEN }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=com.mangopay artifactId=mangopay2-java-sdk version=2.17.0-SNAPSHOT
          assets: extension=jar
          filename: ./build/libs/mangopay2-java-sdk-2.17.0.jar
